<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
  xmlns:msxsl="urn:schemas-microsoft-com:xslt" 
  xmlns:b="http://schemas.openxmlformats.org/officeDocument/2006/bibliography">

  <xsl:output method="html" encoding="us-ascii"/>

  <!-- DEFINITIONS FOR CASE-INSENSITIVE SORTING -->
  <xsl:variable name="lowercase" select="'abcdefghijklmnopqrstuvwxyzäöüàáâèéêìíîòóôùúû'"/>
  <xsl:variable name="uppercase" select="'ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÜÀÁÂÈÉÊÌÍÎÒÓÔÙÚÛ'"/>

  <xsl:template match="/">
    <xsl:call-template name="Start"/>
  </xsl:template>

  <xsl:template name="Start">
    <xsl:choose>
      <xsl:when test="b:Version"><xsl:text>2026.02.17</xsl:text></xsl:when>
      <xsl:when test="b:XslVersion"><xsl:text>2026</xsl:text></xsl:when>
      <xsl:when test="b:StyleNameLocalized"><xsl:text>HAK Steyr - By Nikita Berger</xsl:text></xsl:when>

      <xsl:when test="b:GetImportantFields">
        <b:ImportantFields>
          <b:ImportantField><xsl:text>b:Author/b:Author/b:NameList</xsl:text></b:ImportantField>
          <b:ImportantField><xsl:text>b:Title</xsl:text></b:ImportantField>
          <b:ImportantField><xsl:text>b:Year</xsl:text></b:ImportantField>
          <b:ImportantField><xsl:text>b:URL</xsl:text></b:ImportantField>
        </b:ImportantFields>
      </xsl:when>

      <xsl:when test="b:Bibliography"><xsl:call-template name="Bibliography"/></xsl:when>
      <xsl:when test="b:Citation"><xsl:call-template name="Citation"/></xsl:when>
    </xsl:choose>
  </xsl:template>

  <!-- ================================================================= -->
  <!-- 1. BIBLIOGRAPHY (LITERATURVERZEICHNIS) -->
  <!-- ================================================================= -->
  <xsl:template name="Bibliography">
    <html xmlns="http://www.w3.org/TR/REC-html40">
      <head>
        <style>
          p.MsoBibliography { margin-bottom: 6pt; line-height: 1.5; font-family: Calibri, sans-serif; }
        </style>
      </head>
      <body>
        <xsl:for-each select="b:Bibliography/b:Source">
          <!-- 
             ROBUST SORT LOGIC:
             1. Checks for Author Last Name using // to match any nesting depth.
             2. Ignores the placeholder 'Autor' (generated by your tool) so it falls back to the next field.
             3. Concatenates fields in priority: Real Author -> Corporate -> Company -> Publisher -> Title.
          -->
          <xsl:sort select="translate(concat(
              substring(b:Author//b:Last, 1, string-length(b:Author//b:Last) * number(b:Author//b:Last != 'Autor')), 
              b:Author//b:Corporate, 
              b:ProductionCompany, 
              b:Publisher, 
              b:Title
            ), $lowercase, $uppercase)" />
            
          <xsl:sort select="b:Year"/>
          <xsl:sort select="b:Title"/>

          <p class="MsoBibliography">
            
            <!-- AUTHOR / ORGANIZATION -->
            <xsl:call-template name="BibAuthor">
               <xsl:with-param name="Source" select="."/>
            </xsl:call-template>

            <!-- YEAR -->
            <xsl:text> (</xsl:text>
            <xsl:choose>
              <xsl:when test="string-length(b:Year) > 0"><xsl:value-of select="b:Year"/></xsl:when>
              <xsl:otherwise>o.J.</xsl:otherwise>
            </xsl:choose>
            <xsl:text>): </xsl:text>

            <!-- TITLE -->
            <xsl:value-of select="b:Title"/>
            <xsl:if test="b:SourceType = 'Misc' and (contains(b:Medium, 'YouTube') or contains(b:Title, 'YouTube'))">
               <xsl:text> [YouTube]</xsl:text>
            </xsl:if>
            <xsl:text>. </xsl:text>

            <!-- DETAILS -->
            <xsl:choose>
              <xsl:when test="b:SourceType = 'Book'">
                 <xsl:if test="string-length(b:Edition) > 0">
                    <xsl:value-of select="b:Edition"/><xsl:text>. Aufl., </xsl:text>
                 </xsl:if>
                 <xsl:if test="string-length(b:Publisher) > 0">
                    <xsl:value-of select="b:Publisher"/>
                 </xsl:if>
                 <xsl:text>.</xsl:text>
              </xsl:when>
              <xsl:when test="b:SourceType = 'BookSection'">
                <xsl:text>in: </xsl:text>
                <xsl:call-template name="BibEditor"><xsl:with-param name="Source" select="."/></xsl:call-template>
                <xsl:text> (Hrsg.), </xsl:text>
                <xsl:value-of select="b:BookTitle"/>
                <xsl:if test="string-length(b:City)>0"><xsl:text>, </xsl:text><xsl:value-of select="b:City"/></xsl:if>
                <xsl:if test="string-length(b:Pages)>0"><xsl:text>, S. </xsl:text><xsl:value-of select="b:Pages"/></xsl:if>
                <xsl:text>.</xsl:text>
              </xsl:when>
              <xsl:when test="b:SourceType = 'InternetSite' or b:SourceType = 'DocumentFromInternetSite' or b:SourceType = 'Misc'">
                 <xsl:text>URL: </xsl:text>
                 <xsl:value-of select="b:URL"/>
                 <xsl:text>, Stand: </xsl:text>
                 <xsl:call-template name="FormatDate">
                    <xsl:with-param name="D" select="b:DayAccessed"/>
                    <xsl:with-param name="M" select="b:MonthAccessed"/>
                    <xsl:with-param name="Y" select="b:YearAccessed"/>
                 </xsl:call-template>
                 <xsl:text>.</xsl:text>
              </xsl:when>
              <xsl:when test="b:SourceType = 'JournalArticle'">
                 <xsl:text>in: </xsl:text>
                 <xsl:value-of select="b:JournalName"/>
                 <xsl:text> </xsl:text>
                 <xsl:value-of select="b:Year"/>
                 <xsl:if test="string-length(b:Volume) > 0">
                   <xsl:text>, Jg. </xsl:text><xsl:value-of select="b:Volume"/>
                 </xsl:if>
                 <xsl:if test="string-length(b:Issue) > 0">
                   <xsl:text>, Heft </xsl:text><xsl:value-of select="b:Issue"/>
                 </xsl:if>
                 <xsl:text>, S. </xsl:text>
                 <xsl:value-of select="b:Pages"/>
                 <xsl:text>.</xsl:text>
              </xsl:when>
              <xsl:otherwise>
                 <xsl:if test="string-length(b:City)>0"><xsl:value-of select="b:City"/><xsl:text>.</xsl:text></xsl:if>
              </xsl:otherwise>
            </xsl:choose>
          </p>
        </xsl:for-each>
      </body>
    </html>
  </xsl:template>

  <!-- ================================================================= -->
  <!-- 2. CITATION (KURZBELEG IM TEXT) -->
  <!-- ================================================================= -->
  <xsl:template name="Citation">
    <html xmlns="http://www.w3.org/TR/REC-html40">
      <body>
        <xsl:for-each select="b:Citation">
           <xsl:variable name="Source" select="b:Source"/>
           <xsl:variable name="Comment" select="b:Comments"/>
           <xsl:choose>
             <xsl:when test="contains($Comment, 'direkt')"></xsl:when>
             <xsl:when test="contains($Comment, 'Bild') or contains($Comment, 'bild') or contains($Comment, 'Abb') or contains($Comment, 'Quelle')">
               <xsl:text>Quelle: </xsl:text>
             </xsl:when>
             <xsl:otherwise>
               <xsl:text>Vgl. </xsl:text>
             </xsl:otherwise>
           </xsl:choose>
           
           <xsl:call-template name="CitAuthor">
              <xsl:with-param name="Source" select="$Source"/>
           </xsl:call-template>
           
           <xsl:text> (</xsl:text>
           <xsl:choose>
             <xsl:when test="string-length($Source/b:Year) > 0"><xsl:value-of select="$Source/b:Year"/></xsl:when>
             <xsl:otherwise>o.J.</xsl:otherwise>
           </xsl:choose>
           <xsl:text>)</xsl:text>
           <xsl:choose>
             <xsl:when test="string-length(b:Pages) > 0">
               <xsl:choose>
                 <xsl:when test="contains(b:Pages, ':')">
                   <xsl:text>, </xsl:text><xsl:value-of select="b:Pages"/>
                 </xsl:when>
                 <xsl:otherwise>
                   <xsl:text>, S. </xsl:text><xsl:value-of select="b:Pages"/>
                 </xsl:otherwise>
               </xsl:choose>
             </xsl:when>
             <xsl:when test="$Source/b:SourceType = 'InternetSite' or $Source/b:SourceType = 'DocumentFromInternetSite'">
               <xsl:text>, [Online]</xsl:text>
             </xsl:when>
           </xsl:choose>
           <xsl:text>.</xsl:text>
        </xsl:for-each>
      </body>
    </html>
  </xsl:template>

  <!-- ================================================================= -->
  <!-- HELPERS -->
  <!-- ================================================================= -->

  <!-- A. DISPLAY AUTHOR (Bibliography) -->
  <xsl:template name="BibAuthor">
    <xsl:param name="Source"/>
    <!-- Use // to find person deep in structure OR direct child -->
    <xsl:variable name="Persons" select="$Source/b:Author//b:Person"/>
    <xsl:variable name="Corp" select="$Source/b:Author//b:Corporate"/>
    <!-- Detect Placeholder "Autor, ohne" from tool -->
    <xsl:variable name="IsPlaceholder" select="$Persons[1]/b:Last = 'Autor' and ($Persons[1]/b:First = 'ohne' or $Persons[1]/b:First = 'o.')"/>

    <xsl:choose>
      <xsl:when test="string-length($Corp) > 0">
        <xsl:value-of select="translate($Corp, $lowercase, $uppercase)"/>
      </xsl:when>
      <xsl:when test="count($Persons) > 0 and not($IsPlaceholder)">
        <xsl:for-each select="$Persons">
           <xsl:value-of select="translate(b:Last, $lowercase, $uppercase)"/>
           <xsl:if test="string-length(b:First) > 0">
             <xsl:text>, </xsl:text>
             <xsl:value-of select="b:First"/>
           </xsl:if>
           <xsl:text>.</xsl:text>
           <xsl:if test="position() != last()">
             <xsl:text>/</xsl:text>
           </xsl:if>
        </xsl:for-each>
      </xsl:when>
      <xsl:when test="string-length($Source/b:ProductionCompany) > 0">
         <xsl:value-of select="translate($Source/b:ProductionCompany, $lowercase, $uppercase)"/>
      </xsl:when>
      <xsl:when test="string-length($Source/b:Publisher) > 0">
         <xsl:value-of select="translate($Source/b:Publisher, $lowercase, $uppercase)"/>
      </xsl:when>
      <xsl:otherwise>
         <xsl:text>O.A.</xsl:text>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- B. DISPLAY EDITOR -->
  <xsl:template name="BibEditor">
    <xsl:param name="Source"/>
    <xsl:for-each select="$Source/b:Author/b:Editor//b:Person">
      <xsl:value-of select="b:Last"/>, <xsl:value-of select="b:First"/>
      <xsl:if test="position() != last()"><xsl:text>/</xsl:text></xsl:if>
    </xsl:for-each>
  </xsl:template>

  <!-- C. DISPLAY AUTHOR (Citation) -->
  <xsl:template name="CitAuthor">
    <xsl:param name="Source"/>
    <xsl:variable name="Persons" select="$Source/b:Author//b:Person"/>
    <xsl:variable name="Corp" select="$Source/b:Author//b:Corporate"/>
    <xsl:variable name="Count" select="count($Persons)"/>
    <xsl:variable name="IsPlaceholder" select="$Persons[1]/b:Last = 'Autor' and ($Persons[1]/b:First = 'ohne' or $Persons[1]/b:First = 'o.')"/>

    <xsl:choose>
      <xsl:when test="string-length($Corp) > 0">
        <xsl:value-of select="translate($Corp, $lowercase, $uppercase)"/>
      </xsl:when>
      <xsl:when test="$IsPlaceholder or $Count = 0">
         <xsl:choose>
            <xsl:when test="string-length($Source/b:ProductionCompany) > 0">
               <xsl:value-of select="translate($Source/b:ProductionCompany, $lowercase, $uppercase)"/>
            </xsl:when>
            <xsl:when test="string-length($Source/b:Publisher) > 0">
               <xsl:value-of select="translate($Source/b:Publisher, $lowercase, $uppercase)"/>
            </xsl:when>
            <xsl:otherwise><xsl:text>O.A.</xsl:text></xsl:otherwise>
         </xsl:choose>
      </xsl:when>
      <xsl:when test="$Count = 1">
        <xsl:value-of select="translate($Persons[1]/b:Last, $lowercase, $uppercase)"/>
      </xsl:when>
      <xsl:when test="$Count = 2">
        <xsl:value-of select="translate($Persons[1]/b:Last, $lowercase, $uppercase)"/>
        <xsl:text>/</xsl:text>
        <xsl:value-of select="translate($Persons[2]/b:Last, $lowercase, $uppercase)"/>
      </xsl:when>
      <xsl:when test="$Count > 2">
        <xsl:value-of select="translate($Persons[1]/b:Last, $lowercase, $uppercase)"/>
        <xsl:text> u.a.</xsl:text>
      </xsl:when>
    </xsl:choose>
  </xsl:template>

  <!-- D. DATE FORMATTER -->
  <xsl:template name="FormatDate">
    <xsl:param name="D"/><xsl:param name="M"/><xsl:param name="Y"/>
    <xsl:if test="string-length($D) > 0">
      <xsl:if test="string-length($D) = 1">0</xsl:if>
      <xsl:value-of select="$D"/><xsl:text>.</xsl:text>
    </xsl:if>
    <xsl:if test="string-length($M) > 0">
      <xsl:call-template name="MonthNum"><xsl:with-param name="Mn" select="$M"/></xsl:call-template>
      <xsl:text>.</xsl:text>
    </xsl:if>
    <xsl:value-of select="$Y"/>
  </xsl:template>

  <xsl:template name="MonthNum">
    <xsl:param name="Mn"/>
    <xsl:choose>
      <xsl:when test="$Mn='Januar' or $Mn='January' or $Mn='Jan'">01</xsl:when>
      <xsl:when test="$Mn='Februar' or $Mn='February' or $Mn='Feb'">02</xsl:when>
      <xsl:when test="$Mn='März' or $Mn='March' or $Mn='Mar'">03</xsl:when>
      <xsl:when test="$Mn='April' or $Mn='Apr'">04</xsl:when>
      <xsl:when test="$Mn='Mai' or $Mn='May'">05</xsl:when>
      <xsl:when test="$Mn='Juni' or $Mn='June' or $Mn='Jun'">06</xsl:when>
      <xsl:when test="$Mn='Juli' or $Mn='July' or $Mn='Jul'">07</xsl:when>
      <xsl:when test="$Mn='August' or $Mn='Aug'">08</xsl:when>
      <xsl:when test="$Mn='September' or $Mn='Sep'">09</xsl:when>
      <xsl:when test="$Mn='Oktober' or $Mn='October' or $Mn='Oct'">10</xsl:when>
      <xsl:when test="$Mn='November' or $Mn='Nov'">11</xsl:when>
      <xsl:when test="$Mn='Dezember' or $Mn='December' or $Mn='Dec'">12</xsl:when>
      <xsl:otherwise><xsl:value-of select="$Mn"/></xsl:otherwise>
    </xsl:choose>
  </xsl:template>

</xsl:stylesheet>
